fix: clippy warning and cargo check (#1443)
Closes: #XXX

Fix failures for these checks:

- `cargo check --manifest-path crates/core-driver/Cargo.toml
--no-default-features`
```
error[E0599]: no method named `to_owned` found for struct `SignedMessage<Ctx, <Ctx as informalsystems_malachitebft_core_types::Context>::Proposal>` in the current scope
   --> crates/core-driver/src/proposal_keeper.rs:297:37
    |
297 |             evidence.push((existing.to_owned(), conflicting));
    |                                     ^^^^^^^^ method not found in `SignedMessage<Ctx, <Ctx as informalsystems_malachitebft_core_types::Context>::Proposal>`
    |
```
- `cargo clippy --all-targets`
```
error: this loop never actually loops
  --> crates/test/tests/it/equivocation.rs:14:9
```

---

### PR author checklist

#### Contribution eligibility

- [ ] I am a core contributor, OR I have been explicitly assigned to the
linked issue
- [ ] I have read [CONTRIBUTING.md](/CONTRIBUTING.md) and my PR complies
with all requirements
- [ ] I understand that PRs not meeting these requirements will be
closed without review

#### For all contributors

- [ ] Reference a GitHub issue
- [ ] Ensure the PR title follows the [conventional
commits][conv-commits] spec
- [ ] Add a release note in [`RELEASE_NOTES.md`](/RELEASE_NOTES.md) if
the change warrants it
- [ ] Add an entry in [`BREAKING_CHANGES.md`](/BREAKING_CHANGES.md) if
the change warrants it

#### For external contributors

- [ ] Maintainers of Malachite are [allowed to push changes to the
branch][gh-edit-branch]

[conv-commits]: https://www.conventionalcommits.org/en/v1.0.0/#summary
[gh-edit-branch]:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests